# Generated by Django 4.2.7 on 2024-08-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0002_alter_material_材料"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ファイルパス",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="材料",
            field=models.CharField(
                choices=[
                    ("鋼", "鋼"),
                    ("コンクリート", "コンクリート"),
                    ("ゴム", "ゴム"),
                    ("アスファルト", "アスファルト"),
                    ("塩ビ", "塩ビ"),
                    ("その他", "その他"),
                ],
                max_length=100,
            ),
        ),
    ]
