# Generated by Django 4.2.7 on 2024-08-18 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0003_article_ファイルパス_alter_material_材料"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="カテゴリー",
        ),
    ]
