# Generated by Django 4.2.7 on 2024-08-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0004_remove_article_カテゴリー"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partsname",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="partsname",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
