# Generated by Django 4.2.7 on 2024-08-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0005_alter_partsname_options_partsname_display_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="partsnumber",
            constraint=models.UniqueConstraint(
                fields=("parts_name", "number", "span_number", "infra"),
                name="unique_parts_number",
            ),
        ),
    ]
