# Generated by Django 4.2.7 on 2024-08-29 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0008_partsnumber_article"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fullreportdata",
            name="unique_parts_damage",
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.article",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="fullreportdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "damage_name",
                    "parts_split",
                    "join",
                    "infra",
                    "article",
                    "damage_coordinate_x",
                    "damage_coordinate_y",
                    "span_number",
                    "special_links",
                ),
                name="unique_parts_damage",
            ),
        ),
    ]
