# Generated by Django 4.2.7 on 2024-08-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0009_remove_fullreportdata_unique_parts_damage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullreportdata",
            name="table",
            field=models.ForeignKey(
                default=5, on_delete=django.db.models.deletion.CASCADE, to="infra.table"
            ),
            preserve_default=False,
        ),
    ]
