# Generated by Django 4.2.7 on 2024-09-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0010_fullreportdata_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullreportdata",
            name="unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
