# Generated by Django 4.2.7 on 2024-09-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0011_fullreportdata_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fullreportdata",
            name="unit",
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="four_numbers",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
