# Generated by Django 4.2.7 on 2024-09-03 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0013_partsnumber_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagecomment",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.article",
            ),
        ),
        migrations.AddField(
            model_name="damagelist",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.article",
            ),
        ),
    ]
