# Generated by Django 4.2.7 on 2024-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0014_damagecomment_article_damagelist_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="end_latitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="infra",
            name="end_longitude",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
