# Generated by Django 4.2.7 on 2024-09-04 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0016_bridgepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridgepicture",
            name="damage_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="parts_split",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="picture_coordinate_x",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="picture_coordinate_y",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="span_number",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="table",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="infra.table"
            ),
            preserve_default=False,
        ),
    ]
