# Generated by Django 4.2.7 on 2024-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0017_bridgepicture_damage_name_bridgepicture_parts_split_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridgepicture",
            name="damage_coordinate_x",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="damage_coordinate_y",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
