# Generated by Django 4.2.7 on 2024-09-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0018_bridgepicture_damage_coordinate_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridgepicture",
            name="memo_x",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bridgepicture",
            name="memo_y",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
