# Generated by Django 4.2.7 on 2024-09-04 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0019_bridgepicture_memo_x_bridgepicture_memo_y"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bridgepicture",
            old_name="memo_x",
            new_name="memo",
        ),
        migrations.RemoveField(
            model_name="bridgepicture",
            name="memo_y",
        ),
    ]
