# Generated by Django 5.1 on 2024-10-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0021_alter_infra_路線名_alter_table_dxf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dxf',
            field=models.FileField(upload_to='infra/table/dxf/', verbose_name='dxfファイル'),
        ),
    ]
